lab3_2
MTO-2022-pt/lab3_2 pull request #4
Opened 2022-04-08 16:30 UTC by zgontea

Prowadzący zajęcia: Radosław Adamus
Nr indeksu: 228737
Zadanie dokończone w domu.

2022-04-22 15:49 UTC, radamuspl requested changes

2022-04-22 15:49 UTC, radamuspl commented on src/main/java/edu/iis/mto/time/Order.java
> +    private FakeClock fakeClock;
Kod "produkcyjny" ma fake clock??

2022-04-22 15:49 UTC, radamuspl commented on src/main/java/edu/iis/mto/time/Order.java
> +    public Order(FakeClock fakeClock) {
tu powinien być interfejs - którego implementacja w testach wykorzystuje FakeClock - dlaczego opierać się na typach konkretnych jak można na interfejsie?

2022-06-20 14:44 UTC, zgontea commented
@radamuspl 
Fixed

2023-02-28 08:46 UTC, closed without merging